ROOT = ../..
include $(ROOT)/Target/rules.armm0

APP = vector
SRCS = \
	vec_ast.c \
	vec_env.c \
	vec_eval.c \
	vec_fb.c \
	vec_keys.c \
	vec_lexer.c \
	vec_number.c \
	vec_parser.c \
	vec_value.c \
	vector.c
OBJS = $(SRCS:.c=.o)

all: $(APP) size.report

$(APP): $(CRT0) $(OBJS)
	$(LINKER) $^ -o $@.debug -lm$(PLATFORM) $(LINKER_OPT)
	$(STRIP) $(STRIP_OPT) -o $@ $@.debug

size.report: $(APP)
	ls -l $< > $@

clean:
	rm -f $(OBJS) $(APP) *.debug *.bin *.data *.text size.report

.c.o:
	$(CC) $(CFLAGS) $(COPT) -c -o $@ $<
