#ifndef RF_TYPES_H
#define RF_TYPES_H

#include <stdint.h>

/* Mirrors Spark rfanalyzer/types.go and sniffer_types.go. */

enum rf_data_rate {
	RF_RATE_250K = 0,
	RF_RATE_1M,
	RF_RATE_2M,
};

const char *rf_data_rate_str(enum rf_data_rate r);

enum rf_crc_mode {
	RF_CRC_OFF = 0,
	RF_CRC_1B,
	RF_CRC_2B,
};

const char *rf_crc_mode_str(enum rf_crc_mode c);

enum rf_power_level {
	RF_PWR_MIN = 0,
	RF_PWR_LOW,
	RF_PWR_HIGH,
	RF_PWR_MAX,
};

const char *rf_power_level_str(enum rf_power_level p);

enum rf_setting {
	RF_SETTING_CHAN_LO = 0,
	RF_SETTING_CHAN_HI,
	RF_SETTING_DWELL,
	RF_SETTING_SPEED,
	RF_SETTING_RATE,
	RF_SETTING_CRC,
	RF_SETTING_AUTO_ACK,
	RF_SETTING_POWER,
	RF_SETTING_MAX,
};

enum rf_wf_palette {
	RF_WF_PAL_CYAN = 0,
	RF_WF_PAL_FIRE,
	RF_WF_PAL_GRAY,
	RF_WF_PAL_CUBIC,
};

const char *rf_wf_palette_str(enum rf_wf_palette p);

enum rf_protocol_mode {
	RF_PROTO_DECODED = 0,
	RF_PROTO_RAW,
};

const char *rf_protocol_mode_str(enum rf_protocol_mode m);

enum rf_filter_crc {
	RF_FILTER_CRC_ANY = 0,
	RF_FILTER_CRC_OK,
	RF_FILTER_CRC_BAD,
};

const char *rf_filter_crc_str(enum rf_filter_crc f);

enum rf_filter_channel {
	RF_FILTER_CH_ALL = 0,
	RF_FILTER_CH_SELECTED,
	RF_FILTER_CH_RANGE,
};

const char *rf_filter_channel_str(enum rf_filter_channel f);

enum rf_analysis_view {
	RF_ANALYSIS_CHANNELS = 0,
	RF_ANALYSIS_DEVICES,
	RF_ANALYSIS_TIMING,
	RF_ANALYSIS_COLLISIONS,
	RF_ANALYSIS_CORRELATION,
	RF_ANALYSIS_COMPARISON,
	RF_ANALYSIS_MONITORING,
	RF_ANALYSIS_ANNOTATIONS,
	RF_ANALYSIS_DIAGNOSTICS,
	RF_ANALYSIS_STRESS,
};

const char *rf_analysis_view_str(enum rf_analysis_view v);

/* Matches Spark promptKind. */
enum rf_prompt_kind {
	RF_PROMPT_SET_CHANNEL = 0,
	RF_PROMPT_SET_RANGE_LO,
	RF_PROMPT_SET_RANGE_HI,
	RF_PROMPT_SET_DWELL,
	RF_PROMPT_SET_SCAN_STEP,
	RF_PROMPT_SAVE_PRESET,
	RF_PROMPT_LOAD_PRESET,
	RF_PROMPT_SET_FILTER_ADDR,
	RF_PROMPT_SET_FILTER_PAYLOAD,
	RF_PROMPT_SET_FILTER_AGE,
	RF_PROMPT_SET_FILTER_BURST,
	RF_PROMPT_START_RECORDING,
	RF_PROMPT_LOAD_SESSION,
	RF_PROMPT_LOAD_COMPARE_SESSION,
	RF_PROMPT_REPLAY_SEEK,
	RF_PROMPT_EXPORT_CSV,
	RF_PROMPT_EXPORT_PCAP,
	RF_PROMPT_EXPORT_RFPKT,
	RF_PROMPT_AUTO_NAME,
	RF_PROMPT_AUTO_START_DELAY,
	RF_PROMPT_AUTO_DURATION,
	RF_PROMPT_AUTO_STOP_SWEEPS,
	RF_PROMPT_AUTO_STOP_PACKETS,
	RF_PROMPT_STRESS_PPS,
	RF_PROMPT_STRESS_DURATION,
	RF_PROMPT_ANNOT_TAG,
	RF_PROMPT_ANNOT_NOTE,
	RF_PROMPT_ANNOT_DURATION,
};

enum rf_menu_category {
	RF_MENU_VIEW = 0,
	RF_MENU_RF,
	RF_MENU_CAPTURE,
	RF_MENU_DECODE,
	RF_MENU_DISPLAY,
	RF_MENU_ADVANCED,
	RF_MENU_HELP,
};

enum rf_menu_item_id {
	RF_MENU_ITEM_FOCUS_SPECTRUM = 0,
	RF_MENU_ITEM_FOCUS_WATERFALL,
	RF_MENU_ITEM_FOCUS_RFCONTROL,
	RF_MENU_ITEM_FOCUS_SNIFFER,
	RF_MENU_ITEM_FOCUS_PROTOCOL,
	RF_MENU_ITEM_FOCUS_ANALYSIS,

	RF_MENU_ITEM_TOGGLE_SCAN,
	RF_MENU_ITEM_TOGGLE_WATERFALL,
	RF_MENU_ITEM_TOGGLE_CAPTURE,
	RF_MENU_ITEM_TOGGLE_RECORDING,
	RF_MENU_ITEM_ADD_ANNOT_NOW,
	RF_MENU_ITEM_ADD_ANNOT_SELECTED,
	RF_MENU_ITEM_AUTOMATION_ARM,
	RF_MENU_ITEM_RESET_VIEW,

	RF_MENU_ITEM_LOAD_SESSION,
	RF_MENU_ITEM_EXIT_REPLAY,
	RF_MENU_ITEM_REPLAY_PLAY_PAUSE,
	RF_MENU_ITEM_REPLAY_SEEK,
	RF_MENU_ITEM_REPLAY_SPEED,
	RF_MENU_ITEM_EXPORT_CSV,
	RF_MENU_ITEM_EXPORT_PCAP,
	RF_MENU_ITEM_EXPORT_RFPKT,
	RF_MENU_ITEM_LOAD_COMPARE_SESSION,
	RF_MENU_ITEM_CLEAR_COMPARE,

	RF_MENU_ITEM_SET_CHANNEL,
	RF_MENU_ITEM_SET_RANGE_LO,
	RF_MENU_ITEM_SET_RANGE_HI,
	RF_MENU_ITEM_SET_DWELL,
	RF_MENU_ITEM_SET_SCAN_STEP,

	RF_MENU_ITEM_CYCLE_RATE,
	RF_MENU_ITEM_CYCLE_CRC,
	RF_MENU_ITEM_TOGGLE_AUTO_ACK,
	RF_MENU_ITEM_CYCLE_POWER,

	RF_MENU_ITEM_CYCLE_PALETTE,

	RF_MENU_ITEM_SAVE_PRESET,
	RF_MENU_ITEM_LOAD_PRESET,

	RF_MENU_ITEM_TOGGLE_PROTO_MODE,

	RF_MENU_ITEM_AUTOMATION_CONFIG,
	RF_MENU_ITEM_PRESET_PROFILES,

	RF_MENU_ITEM_OPEN_HELP,
};

enum { RF_RENDER_INTERVAL_TICKS = 33 };

int rf_wrap_enum(int v, int n);

#endif

