#!/bin/sh

endian=
mkfs_v2=
while [ "$1" = "-X" ] || [ "$1" = "-2" ]; do
        if [ "$1" = "-X" ]; then
                endian=-X
        elif [ "$1" = "-2" ]; then
                mkfs_v2=-2
        fi
        shift
done
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
        echo "Syntax: $0 [ -2 ] [ -X ] filename isize bsize"
        echo ""
        echo "For a 1.44MB floppy disk, use isize=64, bsize=2880"
        echo "For a <=32MB hard disk (v1), use isize=256, bsize=65535"
        echo "For >32MB, use -2 (largefs v2) and bsize in 512-byte blocks"
        exit 1
fi
if [ -z "$TARGET" ]; then
        echo "The TARGET was not set."
        exit 1
fi

VERSION=`cat ../../version.mk|grep \ VERSION| rev | cut -d ' ' -f 1 | rev`
sed -e "s/XXX/$VERSION/" <templates/issue >etc-files/issue
./build-filesystem-ng $endian $mkfs_v2 -f $1 -g $2 $3 -p platform-$TARGET
