ROOT = ../..
include $(ROOT)/Target/rules.armm0

APP = mc
SRCS = mc.c
OBJS = $(SRCS:.c=.o)

all: $(APP) size.report

$(APP): $(CRT0) $(OBJS)
	$(LINKER) $^ -o $@.debug -lcurses$(PLATFORM) -ltermcap$(PLATFORM) $(LINKER_OPT)
	$(STRIP) $(STRIP_OPT) -o $@ $@.debug

size.report: $(APP)
	ls -l $< > $@

clean:
	rm -f $(OBJS) $(APP) *.debug *.bin *.data *.text size.report

.c.o:
	$(CC) $(CFLAGS) $(COPT) -c -o $@ $<

